### ISSUE TITLE
How to install this library to Raspberry ?

### ISSUE THREAD

**Issue by ugrdursun** [DFRobot/DFRobot_SHT3x#9]
Hello, I bought the product but could not understand how to install this library and use it with raspi & phyton ??

`, first download the library to Raspberry Pi, then open the routines folder. To execute one routine, demox.py, type python demox.py on the command line. To execute the get_gyro_accel_temp_data.py routine, for example, you need to type:`

I dont think this is  a rich explanation, Where is **routines folder** ? 

```
from DFRobot_SHT3X import *
SHT3X =  DFRobot_SHT3x(iic_addr = 0x45,bus = 1)
```

above is from example but of course I cant import library because i could not install it. Plus, I dont know how wiring should be ...

Any support ? 

Thanks

**Comment by pleasetakeup** [comment]
Sorry for the late reply
1. Enable the I2C device of Raspberry Pi first, otherwise, I2C may fail to communicate normally.
2. Download the library from git, and execute the command in the terminal: `git clone https://github.com/DFRobot/DFRobot_SHT3x,` then download the library to Raspberry Pi
3. Execute the command in the terminal: `cd DFRobot_SHT3x/python/raspberrypi/example/,` select one of the three demos in it to execute such as `python single_measurement.py`
![1](https://user-images.githubusercontent.com/49088278/158950785-d1a3e11e-b10a-4a36-be5e-5f47b86f2a8a.png)

4. The code uses I2C1, so you have to connect the module's SDA and SCL to SDA.1 and SCL.1 of Raspberry Pi respectively. Raspberry Pi pinout is as shown below:
![2](https://user-images.githubusercontent.com/49088278/158951940-ccb19ada-6c73-4ba0-aecc-04867bc08833.png)
